run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: plz
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
  disable:
    - deadcode
    - structcheck

issues:
  exclude-use-default: false
  exclude:
    # Allow fmt.Printf in main commands for output
    - "G104: Errors unhandled"
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck